// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Built4U() {
    driver.Navigate().GoToUrl("https://homeimprovementfeastervilletrevose.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1903, 1032);
    driver.FindElement(By.Id("logo")).Click();
    driver.FindElement(By.CssSelector("#top-menu > #menu-item-1692 > a")).Click();
    driver.FindElement(By.CssSelector("#top-menu > #menu-item-1701 > a")).Click();
    driver.FindElement(By.CssSelector(".wp-image-2145")).Click();
    driver.FindElement(By.CssSelector("#top-menu > #menu-item-1701 > a")).Click();
    driver.FindElement(By.CssSelector("#top-menu > #menu-item-1702 > a")).Click();
    driver.FindElement(By.CssSelector("#top-menu > #menu-item-2189 > a")).Click();
    driver.FindElement(By.CssSelector(".wp-image-2156")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".wp-image-2156"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".mfp-arrow-right")).Click();
    driver.FindElement(By.CssSelector(".mfp-arrow-right")).Click();
    driver.FindElement(By.CssSelector(".mfp-arrow-right")).Click();
    driver.FindElement(By.CssSelector(".mfp-arrow-right")).Click();
    driver.FindElement(By.CssSelector(".mfp-arrow-left")).Click();
    driver.FindElement(By.CssSelector(".mfp-arrow-left")).Click();
    driver.FindElement(By.CssSelector(".mfp-arrow-left")).Click();
    driver.FindElement(By.CssSelector(".mfp-close")).Click();
    driver.FindElement(By.CssSelector("#top-menu > #menu-item-1703 > a")).Click();
    driver.FindElement(By.Id("customer_name")).Click();
    driver.FindElement(By.Id("customer_name")).SendKeys("Tetiana Koziychuk");
    driver.FindElement(By.Id("phone-cf")).SendKeys("2157794239");
    driver.FindElement(By.Id("customer_name")).SendKeys(Keys.Down);
    driver.Close();
  }
}
